### ISSUE TITLE
Not compatible with version IU-223.8214.52

### ISSUE THREAD

**Issue by robertotics4** [getomni/jetbrains#113]
When trying to install the Omni theme in version UI-223.8214.52 I got the following error:

![image](https://user-images.githubusercontent.com/47399431/214041713-909eb902-af02-4ee7-93c5-d570c9563da9.png)

Thanks!

**Comment by felipe-dna** [comment]
Same here, any update?

**Comment by doardin** [comment]
[Omni.Theme-0.1.8.zip](https://github.com/getomni/jetbrains/files/10942081/Omni.Theme-0.1.8.zip) you can try to install using this zip generated by me

**Comment by robertotics4** [comment]
> [Omni.Theme-0.1.8.zip](https://github.com/getomni/jetbrains/files/10942081/Omni.Theme-0.1.8.zip) you can try to install using this zip generated by me

Thanks my brother

**Comment by doardin** [comment]
works fine?

**Comment by IsmaelAbadToaldo** [comment]
same!

Plugin 'Omni Theme' (version '0.1.7') is not compatible with the current version of the IDE, because it requires build 222.* or older but the current build is IU-223.8617.56.

![Screenshot from 2023-03-14 08-04-45](https://user-images.githubusercontent.com/5464827/224996485-6d40da55-dd92-4da5-bfca-36980e1f9f3b.png)

thanks @doardin

**Comment by robertotics4** [comment]
> The solution is here:

https://github.com/getomni/jetbrains/issues/113#issuecomment-1463748279
